### ISSUE TITLE
Cabal/Scrin Voices not in repo.

### ISSUE THREAD

**Issue by SteelPhase** [ABrandau/Shattered-Paradise#1]
mods.yaml `sp|bits/cabal/audio/voice` and `sp|bits/scrin/audio/voice`

**Comment by ABrandau** [comment]
That content is not missing, it has not been done yet, my first priority is the graphics, then balance, then other stuff.

**Comment by ABrandau** [comment]
You never mentioned this lead to a crash, and we fixed said crash a little while ago I believe, real voices will be added when we get those.
